---
- name: "EC2 Lanuncher"
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: "Launching EC2"
      amazon.aws.ec2:
        assign_public_ip: true
        count: 1
        group: default
        image: ami-04d29b6f966df1537
        region: us-east-1
        instance_type: t2.micro
        key_name: Amazon_Key
        vpc_subnet_id: subnet-2cdd7f73
        wait: true

